version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: test_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=change_the_name
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: test
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite


volumes:
  pgdata:
    driver: local
